//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESS.FW.Bpm.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESS.FW.Bpm.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema
        ///  xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  targetNamespace=&quot;http://activiti.org/bpmn&quot;
        ///  xmlns:tns=&quot;http://activiti.org/bpmn&quot;
        ///  elementFormDefault=&quot;qualified&quot;&gt;
        ///  
        ///  &lt;!-- TODO
        ///  
        ///    
        ///       formKey
        ///
        ///       formProperty id=&quot;&quot; type variable expression writable required
        ///                    activiti:value
        ///   --&gt;
        ///
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;
        ///      This XML Schema defines and documents BPMN 2.0 extension elements and
        ///      attributes introduced by Activiti.
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string activiti_bpmn_extensions_5_0 {
            get {
                return ResourceManager.GetString("activiti_bpmn_extensions_5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema
        ///  xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  targetNamespace=&quot;http://activiti.org/bpmn&quot;
        ///  xmlns:tns=&quot;http://activiti.org/bpmn&quot;
        ///  xmlns:sem=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;
        ///  elementFormDefault=&quot;qualified&quot;&gt;
        ///  
        ///&lt;import namespace=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; schemaLocation=&quot;Semantic.xsd&quot; /&gt;  
        ///
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;
        ///      This XML Schema defines and documents BPMN 2.0 extension elements and
        ///      attributes introduced by A [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string activiti_bpmn_extensions_5_10 {
            get {
                return ResourceManager.GetString("activiti_bpmn_extensions_5_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema
        ///  xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  targetNamespace=&quot;http://activiti.org/bpmn&quot;
        ///  xmlns:tns=&quot;http://activiti.org/bpmn&quot;
        ///  elementFormDefault=&quot;qualified&quot;&gt;
        ///  
        ///  &lt;!-- TODO
        ///  
        ///    
        ///       formKey
        ///
        ///       formProperty id=&quot;&quot; type variable expression writable required
        ///                    activiti:value
        ///   --&gt;
        ///
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;
        ///      This XML Schema defines and documents BPMN 2.0 extension elements and
        ///      attributes introduced by Activiti.
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string activiti_bpmn_extensions_5_2 {
            get {
                return ResourceManager.GetString("activiti_bpmn_extensions_5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema
        ///  xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  targetNamespace=&quot;http://activiti.org/bpmn&quot;
        ///  xmlns:tns=&quot;http://activiti.org/bpmn&quot;
        ///  elementFormDefault=&quot;qualified&quot;&gt;
        ///  
        ///  &lt;!-- TODO
        ///  
        ///    
        ///       formKey
        ///
        ///       formProperty id=&quot;&quot; type variable expression writable required
        ///                    activiti:value
        ///   --&gt;
        ///
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;
        ///      This XML Schema defines and documents BPMN 2.0 extension elements and
        ///      attributes introduced by Activiti.
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string activiti_bpmn_extensions_5_3 {
            get {
                return ResourceManager.GetString("activiti_bpmn_extensions_5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;schema
        ///  xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///  targetNamespace=&quot;http://activiti.org/bpmn&quot;
        ///  xmlns:tns=&quot;http://activiti.org/bpmn&quot;
        ///  xmlns:sem=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;
        ///  elementFormDefault=&quot;qualified&quot;&gt;
        ///  
        ///&lt;import namespace=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot; schemaLocation=&quot;Semantic.xsd&quot; /&gt;  
        ///  
        ///  &lt;!-- TODO
        ///  
        ///    
        ///       formKey
        ///
        ///       formProperty id=&quot;&quot; type variable expression writable required
        ///                    activiti:value
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string activiti_bpmn_extensions_5_4 {
            get {
                return ResourceManager.GetString("activiti_bpmn_extensions_5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;
        ///	xmlns=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;
        ///	xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot;
        ///	targetNamespace=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;&gt;
        ///
        ///	&lt;xsd:import namespace=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; schemaLocation=&quot;BPMNDI.xsd&quot;/&gt;
        ///	&lt;xsd:include schemaLocation=&quot;Semantic.xsd&quot;/&gt;
        ///
        ///	&lt;xsd:element name=&quot;definitions [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BPMN20 {
            get {
                return ResourceManager.GetString("BPMN20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:bpmndi=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; targetNamespace=&quot;http://www.omg.org/spec/BPMN/20100524/DI&quot;  elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xsd:import namespace=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; schemaLocation=&quot;DC.xsd&quot; /&gt;
        ///	&lt;xsd:import namespace=&quot;http://www.omg.or [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BPMNDI {
            get {
                return ResourceManager.GetString("BPMNDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; targetNamespace=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xsd:element name=&quot;Font&quot; type=&quot;dc:Font&quot; /&gt;
        ///	&lt;xsd:element name=&quot;Point&quot; type=&quot;dc:Point&quot; /&gt;
        ///	&lt;xsd:element name=&quot;Bounds&quot; type=&quot;dc:Bounds&quot; /&gt;
        ///	
        ///	&lt;xsd:complexType name=&quot;Font&quot;&gt;
        ///		&lt;xsd:attribute name=&quot;name&quot; type=&quot;xsd:string&quot; /&gt;
        ///		&lt;xsd:attribute nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DC {
            get {
                return ResourceManager.GetString("DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:dc=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; xmlns:di=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; targetNamespace=&quot;http://www.omg.org/spec/DD/20100524/DI&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///
        ///	&lt;xsd:import namespace=&quot;http://www.omg.org/spec/DD/20100524/DC&quot; schemaLocation=&quot;DC.xsd&quot; /&gt;
        ///	
        ///	&lt;xsd:element name=&quot;DiagramElement&quot; type=&quot;di:DiagramElement&quot; /&gt;
        ///	&lt;xsd:element name=&quot;Diagram&quot; type= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DI {
            get {
                return ResourceManager.GetString("DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;
        ///	xmlns=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;
        ///	xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	targetNamespace=&quot;http://www.omg.org/spec/BPMN/20100524/MODEL&quot;&gt;
        ///
        ///	&lt;xsd:element name=&quot;activity&quot; type=&quot;tActivity&quot;/&gt;
        ///	&lt;xsd:complexType name=&quot;tActivity&quot; abstract=&quot;true&quot;&gt;
        ///		&lt;xsd:complexContent&gt;
        ///			&lt;xsd:extension base=&quot;tFlowNode&quot;&gt;
        ///				&lt;xsd:sequence&gt;
        ///					&lt;xsd:element ref=&quot;ioSpecification&quot; minOccurs=&quot;0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Semantic {
            get {
                return ResourceManager.GetString("Semantic", resourceCulture);
            }
        }
    }
}
